name: skyfinder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - tensorboard
  - pip
  - pip:
      - tabpfn
      - transformers
      - datasets
      - evaluate
      - accelerate
      - timm
      - wandb
      - tensorboard-logger
      - opencv-python
      - imgaug